runtime: python311
service: default

env_variables:
  # API Settings
  API_V1_STR: "/api/v1"
  PROJECT_NAME: "A-Live-Grid"
  
  # Security - Change this in production!
  SECRET_KEY: "your-super-secret-key-change-this-in-production"
  
  # Security
  ACCESS_TOKEN_EXPIRE_MINUTES: "11520"
  
  # File Upload Settings
  UPLOAD_DIR: "uploads"
  MAX_FILE_SIZE: "10485760"
  
  # Agent Configuration (optional - set these if using OpenAI)
  # OPENAI_API_KEY: "your-openai-api-key"
  OPENAI_MODEL_NAME: "gpt-4.1"
  
  # LangSmith Configuration (optional)
  LANGSMITH_TRACING: "false"
  # LANGSMITH_ENDPOINT: "https://api.smith.langchain.com"
  # LANGSMITH_API_KEY: "your-langsmith-api-key"
  # LANGSMITH_PROJECT: "your-project-name"
  
  # Flask Configuration
  FLASK_DEBUG: "false"
  FLASK_ENV: "production"

handlers:
  # Serve static files (if any)
  - url: /static
    static_dir: static
    
  # Serve uploaded images
  - url: /uploads
    static_dir: uploads
    
  # All other requests go to the FastAPI app
  - url: /.*
    script: auto

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker run:app --bind :$PORT 